user:file_search_path(tekstoj,'../txt').
user:file_search_path(verkoj,'../xml').

bib(pv,'PrV').
bib(ee,'EE').
bib(ma,'Marta').
bib(ba,'BdV').
bib(dl,'DL').
bib(fk,'FK').
bib(op,'FdO').
bib(ha,'Hamlet').
bib(if,'Ifigenio').
bib(ik,'IK').
%bib(lr,'LR').
bib(vz,'VivZam').
   
% klasikaj tekstoj de Zamnenhof, Kabe, Ŝvarc
vrk(pv,proverbaro,
    struct_teix(preface,chapter),
    verkoj('proverb.xml')).
vrk(mt,biblio_malnova,
    struct_biblio,
    tekstoj('biblio/malnova/*.utf')).
vrk(nt,biblio_nova,
    struct_biblio,
    tekstoj('biblio/nova/*.utf')).
vrk(fb,fabeloj,
    struct_teix(foreword,story),
    verkoj('fabeloj?.xml')).
vrk(fr,faraono,
    struct_teix(chapter),
    verkoj('faraono?.xml')).
vrk(fe,fundamento,
    struct_fundamento,
    verkoj('fundamento.xml')).
vrk(gf,gfabeloj,
    struct_teix(foreword,story),
    verkoj('gfabeloj.xml')).
vrk(ik,interompita,
    struct_teix(chapter),
    verkoj('interrompita.xml')).
vrk(ee,esenco,
    struct_teix(chapter),
    verkoj('esenco.xml')).
vrk(hm,homaranismo,
    struct_paroloj,
    verkoj('homaranismo.xml')).
vrk(op,opiofumejo,
    struct_teix(novel),
    verkoj('fumejo.xml')).
vrk(pa,paroloj,
    struct_paroloj,
    verkoj('paroloj.xml')).
vrk(po,poemoj,
    struct_teix(poem),
    verkoj('poemoj.xml')).
vrk(bu,butiko,
    struct_teix(foreword,poem),
    verkoj('butiko.xml')).
vrk(ma,marta,
    struct_marta,
    verkoj('marta.xml')).
vrk(rv,revizoro,
    struct_teix(act),
    verkoj('revizoro.xml')).
vrk(ra,rabistoj,
    struct_teix(act),
    verkoj('rabistoj.xml')).

vrk(ba,batalo,
    struct_gutenberg,
    tekstoj('gutenberg/Batalo_de_Vivo.html')).
vrk(dl,dualibro,
    struct_gutenberg,
    tekstoj('gutenberg/Dua_Libro.html')).
vrk(fk,krestomatio,
    struct_gutenberg,
    tekstoj('gutenberg/Krestomatio.html')).
vrk(ha,hamleto,
    struct_gutenberg,
    tekstoj('gutenberg/Hamleto.html')).
vrk(if,ifigenio,
    struct_gutenberg,
    tekstoj('gutenberg/Ifigenio.html')).
vrk(lr,lingvaj_respondoj,
    struct_teix_nevalida(parto),
    tekstoj('tekstaro/LingvajRespondoj.xml')).
vrk(vz,vivozamenhof,
    struct_gutenberg,
    tekstoj('gutenberg/Vivo_de_Zamenhof.html')).

% postaj tekstoj
vrk(m1,monato_1,
    struct_monato_txt,
    tekstoj('monato/*.txt')).
vrk(m2,monato_2,
    struct_monato_html,
    tekstoj('monato2/html/*.html')).
vrk(m3,monato_3,
    struct_monato_html,
    tekstoj('monato3/*/0*.*')).

vrk(sr,senchesa,
    struct_teix(chapter),
    verkoj('senchesa*.xml')). % per la * ignoriĝas, se mankas!

verkaro(klasikaj,[pv,mt,nt,fb,gf,fr,fe,ee,ik,hm,pa,po,bu,ma,ha,ba,op,rv,ra,vz,if,lr,fk,dl]).
verkaro(postaj,[m1,m2,m3,sr]).
verkaro(chiuj,Verkoj) :- findall(V,vrk(V,_,_,_),Verkoj).
