#!/bin/bash

# Tio estas la eldono de voko-cikado
eldono=2p

target="${1:-helpo}"


# aldonu en /etc/hosts!
host=revo
revo=${host}:www/revo
cgibin=${host}:www/cgi-bin

case $target in
preparo)
    # kontrolu la branĉonomon kaj komparu kun eldono
    branch=$(git symbolic-ref --short HEAD)
    if [ "${branch}" != "${eldono}" ]; then
        echo "Ne kongruas la branĉo (${branch}) kun la eldono (${eldono})"
        echo "Agordu la variablon 'eldono' en tiu ĉi skripto por prepari novan eldonon."
        exit 1
    fi
    echo "Nenio farenda por preparo."
    ;;
kreo)
    echo "Kreante lokan procezujon (por docker) voko-cikado"
    #docker build --build-arg VERSION=${eldono} --build-arg VG_TAG=v${eldono} --build-arg ZIP_SUFFIX=${eldono} \
    #    -t voko-cikado .
    docker build -t voko-cikado .
    ;;
etikedo)
    echo "Provizante la aktualan staton per etikedo (git tag) v${eldono}"
    echo "kaj puŝante tiun staton al la centra deponejo"
    git tag -f v${eldono} && git push && git push origin v${eldono} -f
    ;;   
ofc)
    scp ./steloj.de/fundamento/fundamento.json ${revo}/inx
    scp ./steloj.de/ofcaldonoj/ofcaldonoj.json ${revo}/inx
    echo "poste voku https://retavortaro.de/cgi-bin/admin/upofc.pl"
    ;;     
helpo | *)
    echo "---------------------------------------------------------------------------"
    echo "Per la celo 'kreo' oni povas krei docker-procezujon de voko-cikado. "
    echo "Per etikedo vi etikedas la aktualan staton per la eldono (adaptebla variablo supre en la skripto)"
    echo "kaj puŝas tion al Github, per kio tie kreiĝas aktuala procezujo kun tiu eldono."
    ;;    
esac
